### ISSUE TITLE
Support for Map type in Parquet/Hive source and sinks

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#205] opened 2017-01-05 15:16 UTC
- This equates to the _Parquet_ **org.apache.parquet.schema.OriginalType.MAP** nested type - see https://github.com/apache/parquet-format/blob/master/LogicalTypes.md
- The following example demonstrates the type for a non-null map from strings to nullable integers:

// Map<String, Integer>
required group my_map (MAP) {
  repeated group key_value {
    required binary key (UTF8);
    optional int32 value;
  }
}
- Note like the **Array** support the value type could be any primitive or structured type.

- The following describe how to query structured types in Impala and HiveQL respectively:

https://www.cloudera.com/documentation/enterprise/5-5-x/topics/impala_complex_types.html
https://joshuafennessy.com/2015/07/09/introduction-to-hive-complex-data-types-part-1-array/

**Comment by sksamuel** [comment] 2017-01-05 22:12
Duplicate of #189

**Closed as completed** 2017-01-16 01:54 UTC
Labels: enhancement
