### ISSUE TITLE
Add support for impala

### ISSUE THREAD

**Issue by Antwnis** [51zero/eel-sdk#23] opened 2016-01-28 20:44 UTC
By passing in `authmech=3` and user/pass in the jdbc url you can interact with Impala even when Kerberos is enabled

**Comment by sksamuel** [comment] 2016-01-28 23:39
This can be done by changing the jdbc url ?

**Comment by Antwnis** [comment] 2016-01-29 12:47
Build two aliases ImpalaSource / ImpalaSink

```
JDBCDriver = "com.cloudera.impala.jdbc3.Driver"
jdbc:impala://host:21050;AuthMech=3;UID=UserName;PWD=Password
```

**Comment by sksamuel** [comment] 2016-01-29 12:49
Why can't you do JdbcSource("jdbc:impala://host:21050;
AuthMech=3;UID=UserName;PWD=Password") ?

**Comment by sksamuel** [comment] 2016-01-31 22:52
This is a duplicate of functionality already present in jdbc source

**Closed as completed** 2016-01-31 22:52 UTC
