### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by tolomaus** [51zero/eel-sdk#180] opened 2016-11-24 09:55 UTC
Hi,

I tested the ParquetSource on a parquet file of about 5M records, split in 144 partitions (files) on an 8 CPU server in the default way:
``` scala
    ParquetSource(new Path(modelPath))
      .toFrame(16)
      .toList
      .map(convertRow)
```

After about 10 min the process got stuck and I had to kill it. All cpu's were at 100% for the whole duration

I then tested with a slightly modified codebase:
``` scala
    ParquetSource(new Path(modelPath))
      .parts
      .par
      .flatMap { part =>
        part.data
          .map(convertRow)
          .toList.toBlocking.single
      }
```

And that finished the job in 30 sec. Even without the ```.par``` line it still only takes 2 min (running on a single cpu)

Any idea why the two implementations give so different results?

**Comment by sksamuel** [comment] 2016-11-24 10:02
Possibly some kind of infinite loop error. I'll look into it.

**Comment by sksamuel** [comment] 2016-11-26 12:44
Do you have a sample file? If not, can you tell me how unique the data is (how many values are repeated roughly)

**Comment by tolomaus** [comment] 2016-11-26 13:10
The input file contains words with an array of doubles:

```scala
  private def convertRow(row: Row) = {
    val word = row.values(0).asInstanceOf[String]
    val vector = row.values(1).asInstanceOf[util.ArrayList[Double]].toArray.map(_.asInstanceOf[Record].get(0).asInstanceOf[Double])
    (word, new DenseVector(vector))
  }
```

All words are unique.

Let me know if there's anything else I can do to help. Thanks!

**Comment by tolomaus** [comment] 2016-11-30 10:07
After upgrading to 1.1.0-snapshot I had to slightly modify my workaround solution as the part was changed from Observable to Flux: 
```scala
    ParquetSource(new Path(modelPath))
      .parts
      .par
      .flatMap { part =>
        logger.info(s"Loading part...")
        part.data
          .toIterable.asScala
          .map(convertRow)
      }
```

But that gives a huge performance hit: the 5 million records are loaded now in 1m40s min compared to 30s before. Just wanted to let you know.

**Comment by sksamuel** [comment] 2016-11-30 10:36
That's interesting. I think the .toIterable is blocking and slow. I certainly won't publish anything in 1.1.0 that's not up to scratch. I've been playing about with https://projectreactor.io/ as an alternative to RxJava1 that I was using before.

**Comment by sksamuel** [comment] 2016-12-05 12:06
@tolomaus so I know the reason for the slowness now, the reactor-core and rxjava frameworks use recursion when merging together multiple observables. If you have 100 files say, you have 100 levels of recursion for every single row. I'll be switching that out this week.

**Comment by tolomaus** [comment] 2016-12-05 12:53
Good spot! As soon as this change is made I will switch back to the latest version on github and try it out.

**Comment by sksamuel** [comment] 2016-12-07 02:22
Want to try that latest snapshot see what your results are?

**Comment by tolomaus** [comment] 2016-12-07 09:58
Looks good!

I currently don't have the full dataset of 5M words available but I tested with roughly a fifth of it. With the previous version the load took 15s and with the latest version it only takes 10s!
 
I will let you know the figures once I have my 5M dataset back.

One note: as I want to run parallel calculations based on the loaded dataset, I prefer to keep it split up in a ParMap. The ```parts``` api allows me to do this so I'm not using the ``toFrame``` api. I noticed however that the latest version is less straightforward to collect all rows per part:

```scala
    ParquetSource(new Path(path))
      .parts
      .par
      .flatMap { part =>
        var rowsTotal = List[Row]()
        part.iterator.foreach { rows =>
          rowsTotal = rowsTotal ++ rows
        }
        ...
      }
```

Is this the best way to proceed?

Thanks!

**Comment by sksamuel** [comment] 2016-12-07 10:00
Yes you can do that, or the Frame API will allow you to multi-thread the
code in the next release as well. The reason for the List[Row] is that it
avoids a lot of the contention on the locks.

**Comment by sksamuel** [comment] 2016-12-14 09:21
I've released another snapshot. There's no more reactive framework slowing it down in the middle. Also, the `ParquetSource` is now a native parquet source (no avro middle man), and the newly added `AvroParquetSource` is what was called ParquetSource before. The new one is not well tested yet, and the type mappings might still need correction. @hannesmiller @tolomaus @stheppi

**Comment by tolomaus** [comment] 2016-12-23 15:39
My version of parquet somehow got bumped from 1.8.1 to 1.9.0 today which threw an error while parsing the data: 

```
Caused by: java.lang.ClassCastException: org.apache.parquet.example.data.simple.SimpleGroup cannot be cast to org.apache.parquet.example.data.simple.BinaryValue
	at org.apache.parquet.example.data.simple.SimpleGroup.getString(SimpleGroup.java:124)
	at io.eels.component.parquet.ParquetDeserializer$$anonfun$toRow$1.apply(ParquetDeserializer.scala:47)
	at io.eels.component.parquet.ParquetDeserializer$$anonfun$toRow$1.apply(ParquetDeserializer.scala:34)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at io.eels.component.parquet.ParquetDeserializer.toRow(ParquetDeserializer.scala:34)
	at io.eels.component.parquet.ParquetDeserializer$$anonfun$toRow$1.apply(ParquetDeserializer.scala:46)
	at io.eels.component.parquet.ParquetDeserializer$$anonfun$toRow$1.apply(ParquetDeserializer.scala:34)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at io.eels.component.parquet.ParquetDeserializer.toRow(ParquetDeserializer.scala:34)
	at io.eels.component.parquet.ParquetPart$$anon$1$$anonfun$1$$anonfun$apply$1.apply(ParquetPart.scala:21)
```

I was still using the initial 1.1.0 snapshot and I'm not sure what triggered this bump, nor how I can revert it to the working situation. So I'm back now to eel version 1.0.1 until I have a bit more time to investigate this issue.

The parquet file was generated by spark which is still using parquet 1.7.0, maybe there are backward compatibility issues between 1.7.0 and 1.9.0.

**Comment by sksamuel** [comment] 2017-01-06 02:25
@tolomaus Hope you had a nice Christmas.

Release 1.1.0-M2 has a new native parquet reader/writer, which skips avro and goes directly from parquet to eel row for extra performance. @hannesmiller and I have also spent a lot of time going over the parquet spec to ensure we're compliant, and I've added spark compatibility tests also. Give it a go and see how you get on - if there's any niggles with type conversions (or anything else) paste them up.

**Comment by sksamuel** [comment] 2017-01-06 02:26
I should add, if you want to use the original avro based parquet source and sink, you can, `AvroParquetSource(path)` and `AvroParquetSink(path)`. The new ones are the names as before, `ParquetSource` and `ParquetSink`. The issues you were seeing between 1.7 and 1.9 parquet I actually think was caused by the fact the latest snapshot had a half finished version of the new native reader.

**Comment by tolomaus** [comment] 2017-01-06 08:57
Thanks merry Christmas and happy new year for you and the awesome eel team as well! ;-)

I upgraded spark from 2.0.2 to 2.1.0 yesterday and noticed they have also bumped their parquet dependency from 1.7 to 1.8.1. But I guess the parquet versioning may not be the root cause if I used a half finished reader.

Anyway, I will upgrade my eel dependency to 1.1.0-M2 and see how it goes.

(btw I see quite some people starting to use spark job server to access their offline generated datasets in an online - think web server - context. Imo eel is a much better, more lightweight solution. Do you also see these two approaches as alternatives?)

**Comment by hannesmiller** [comment] 2017-01-06 09:38
Hi Niek,

For our initial Ingestion requirements into our Hadoop cluster I am not sure what sure what added value the Spark Job Server is going to give us on the project Sam and I working on?

We ingest flat CSV files or Oracle datasets coming from upstream systems.

Having said that we extensively use  Spark for parallel processing the datasets already resident in HDFS.

The datasets got their in the first place via EEL however we do create materialised views (or derived datasets) based on the original data - for this we simply use the Spark save API.

We launch individual Spark jobs for our calculation and reporting requirements - we create a Spark context for each job.

The advantage for us is we can specifically tune each job for the required resources and relinquish them when the job has finished - which keeps everyone happy in a multi-tenant cluster environment.

The disadvantage I guess is the initial start up time for each discrete spark job - if you have a long running server with all the resources pre-allocated then each job is going to be quicker. In addition you can cache your Spark Datasets.

But how much of the resources (CPU, RAM) are you going to allocate? Remember long running processes means you take them away from others.

I believe Spark Job Server is a long running process with pre-allocated resources?

However the Spark Job Server looks interesting because it looks lightweight due to its Rest interface and the fact you can cache and share DataFrames/Datasets for multiple users.

We are looking at Apache Ignite caching to achieve this for our own needs.

Regards,
Hannes

**Comment by tolomaus** [comment] 2017-01-06 21:35
Hi Hannes,

Thanks for your explanations. I was specifically referring to using the spark job server as a "Spark as a Query Engine" i.e. loading a parquet file in memory and querying it in multi user mode, compared to simply using eel for this. 

I don't see any value in using spark job server either, though I see some people doing it e.g. https://aws.amazon.com/blogs/big-data/installing-and-running-jobserver-for-apache-spark-on-amazon-emr/

**Comment by tolomaus** [comment] 2017-01-06 21:43
I switched to 1.1.0-M2 but ran into an error when loading the parquet:

```
Execution exception[[ParquetDecodingException: Can not read value at 0 in block -1 in file file:/data/parquet/en/W2vWordVectors/part-r-00060-a49d7a26-5434-4314-9c15-295089627380.snappy.parquet]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:293)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
Caused by: org.apache.parquet.io.ParquetDecodingException: Can not read value at 0 in block -1 in file file:/data/parquet/en/W2vWordVectors/part-r-00060-a49d7a26-5434-4314-9c15-295089627380.snappy.parquet
	at org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:223)
	at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:122)
	at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:126)
	at io.eels.component.parquet.util.ParquetIterator$$anonfun$apply$1.apply(ParquetIterator.scala:10)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:162)
	at scala.collection.Iterator$$anon$16.hasNext(Iterator.scala:598)
	at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:1126)
	at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:1132)
	at io.eels.CloseableIterator$$anon$1.hasNext(CloseableIterator.scala:10)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
Caused by: java.lang.RuntimeException: Unsupported type StructType(Vector(Field(list,StructType(Vector(Field(element,io.eels.schema.DoubleType$@70c66b76,false,false,None,Map()))),false,false,None,Map())))
	at scala.sys.package$.error(package.scala:27)
	at io.eels.component.parquet.RowRecordMaterializer$$anon$1.getConverter(RowReadSupport.scala:64)
	at org.apache.parquet.io.RecordReaderImplementation.<init>(RecordReaderImplementation.java:266)
	at org.apache.parquet.io.MessageColumnIO$1.visit(MessageColumnIO.java:140)
	at org.apache.parquet.io.MessageColumnIO$1.visit(MessageColumnIO.java:106)
	at org.apache.parquet.filter2.compat.FilterCompat$NoOpFilter.accept(FilterCompat.java:154)
	at org.apache.parquet.io.MessageColumnIO.getRecordReader(MessageColumnIO.java:106)
	at org.apache.parquet.hadoop.InternalParquetRecordReader.checkRead(InternalParquetRecordReader.java:136)
	at org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:194)
	at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:122)
```

Here is my code:
```scala
ParquetSource(new Path(wordVectorPath))
      .parts
      .par
      .flatMap { part =>
        var rowsTotal = List[Row]()
        part.iterator.foreach { rows =>
          rowsTotal = rowsTotal ++ rows
        }
        rowsTotal.map(convertWordVectorRow)
      }

  private def convertWordVectorRow(row: Row) = {
    val word = row.values(0).asInstanceOf[String]
    val vector = row.values(1).asInstanceOf[util.ArrayList[Double]].toArray.map(_.asInstanceOf[Record].get(0).asInstanceOf[Double])
    val label = row.values(2).asInstanceOf[String]
    val existsAsRealWordInVocabulary = row.values(3).asInstanceOf[Boolean]
    ...
}
```

The parquet file is still v1.7 but I will rerun the model with spark 2.1 and try again with the regenerated parquet 1.8.1 file, just to be sure.

**Comment by hannesmiller** [comment] 2017-01-06 23:10
-  I see...we use out Apache Zeppelin which has a nice SQL query interpreter for Hive.

- The Scala interactive interpreter allows you load the Parquet Files, Register a temp table and perform SQL on it the temp table

**Comment by sksamuel** [comment] 2017-01-06 23:25
This is the error affecting @tolomaus 

```
java.lang.RuntimeException: Unsupported type StructType(Vector(Field(list,StructType(Vector(Field(element,io.eels.schema.DoubleType$@70c66b76,false,false,None,Map()))),false,false,None,Map())))
	at scala.sys.package$.error(package.scala:27)
	at io.eels.component.parquet.RowRecordMaterializer$$anon$1.getConverter(RowReadSupport.scala:64)
```

**Comment by sksamuel** [comment] 2017-01-06 23:26
BTW orc.apache.org support is now slightly faster than Parquet. Seems they're doing a good job on it and doing regular releases.

**Comment by sksamuel** [comment] 2017-01-12 12:29
Hi @tolomaus. Thanks for your continued testing. Do you want to give M3 a quick go?

**Comment by sksamuel** [comment] 2017-01-12 17:22
Or even better, try 1.1.0 final.

**Comment by tolomaus** [comment] 2017-01-12 19:21
I slightly modified the line that converts the vector, an Array of Doubles:

```scala
val vector = row.values(1).asInstanceOf[Vector[Double]].toArray
```

but I get an error:
```
java.lang.ClassCastException: scala.collection.immutable.Vector cannot be cast to java.lang.Double
```

Looking at it in debug mode I see that something is wrong with the structure of the data: the first item in the vector is correctly defined as a double, but the rest are vector(double)'s instead of simply doubles

E.g.:
(Vector(-0.089236, Vector(-0.08471), Vector(-0.05365), Vector(-0.030827), ...

**Comment by sksamuel** [comment] 2017-01-12 19:37
Is this an existing file you're reading in, or a new file you're writing out? Because I can't see immediately why this would break, but saying that my tests are only checking the string case.

https://github.com/sksamuel/eel-sdk/blob/master/eel-components/src/test/scala/io/eels/component/parquet/ParquetComponentTest.scala#L78-L103

I'll add another test for doubles and post back.

**Comment by sksamuel** [comment] 2017-01-12 19:43
Ok test added.
https://github.com/sksamuel/eel-sdk/blob/master/eel-components/src/test/scala/io/eels/component/parquet/ParquetComponentTest.scala#L104-L129

If the data was written out with an earlier snapshot version of eel, I'd re-write it to be sure. If it was created outside of eel then it must be a bug and maybe its in processing the nested schema. Are you able to paste up your schema, obfuscate the names if you have to, its just the structure that's important.

**Comment by tolomaus** [comment] 2017-01-12 19:48
I'm only reading files. I double checked the file contents using spark and it looks fine from there:

```
+-----------+--------------------+
|       word|              vector|
+-----------+--------------------+
|clienthandl|[-0.079246, 0.050...|
+-----------+--------------------+
```

Here is the eel schema:
StructType(Vector(Field(word,io.eels.schema.StringType$@45045889,true,false,None,Map()), Field(vector,StructType(Vector(Field(list,ArrayType(StructType(Vector(Field(element,io.eels.schema.DoubleType$@5ee7b56d,false,false,None,Map())))),true,false,None,Map()))),true,false,None,Map()), Field(label,io.eels.schema.StringType$@45045889,true,false,None,Map()), Field(existsAsRealWordInVocabulary,io.eels.schema.BooleanType$@67ac493c,true,false,None,Map())))

**Comment by tolomaus** [comment] 2017-01-12 19:50
See here the schema from spark:

StructType(StructField(word,StringType,true), StructField(vector,ArrayType(DoubleType,true),true), StructField(label,StringType,true), StructField(existsAsRealWordInVocabulary,BooleanType,true))

**Comment by sksamuel** [comment] 2017-01-12 20:00
Thanks I'll create a file that mimivs this schema in spark and then try
reading. I suspect the error is in the code that combines values to form
vectors.

**Comment by tolomaus** [comment] 2017-01-12 20:05
I got it to work by removing the head:
```scala
val vector = row.values(1).asInstanceOf[Vector[Any]].tail.map(_.asInstanceOf[Double]).toArray
```
 So it looks like there first item from the vector should also be a Vector(double), just like the other items

**Comment by sksamuel** [comment] 2017-01-12 20:10
Ahh that makes more sense. Hows the performance?

**Comment by tolomaus** [comment] 2017-01-12 20:17
Slightly slower: 16s compared to 13s in 1.0.1. This is for about 800000 items. Not what we expected :-) 1.1.0 uses a more "native" api right? Strange...

**Comment by sksamuel** [comment] 2017-01-12 20:21
Slower but 13 is quicker than 16 lol

**Comment by tolomaus** [comment] 2017-01-12 20:22
see my edited post ;-)

**Comment by sksamuel** [comment] 2017-01-12 20:26
Do you want to try the AvroParquetSource

**Comment by tolomaus** [comment] 2017-01-12 20:31
Sure, I switched to AvroParquetSource, but it looks like it uses the ArrayList from 1.0.1:
```
Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to scala.collection.immutable.Vector
```

I will see if I can fix it tomorrow and get back with the results

**Comment by sksamuel** [comment] 2017-01-12 20:33
Ahh yeah course.

**Comment by sksamuel** [comment] 2017-01-12 23:04
Should cast to a Seq really because no guarantee you'll get a Vector out of the sources. I tend to return those, but if the underlying library returns an Array I reuse that rather than convert to a Scala col.

**Comment by tolomaus** [comment] 2017-01-13 08:43
Ok thanks. Would be good if we could map the source format directly to a case class and let the library take care of the conversion ceremony. 

Is that something you could add to this library as well? Maybe through avro4s? Or as a quick alternative expose a GenericRecord so I can pass that myself to avro4s?

```scala
val ennio = format.from(record)
```

**Comment by sksamuel** [comment] 2017-01-13 09:03
Yes that's a good idea and one touched upon before. I'll be adding that for 1.2.
I'm about to release 1.1.1 which has the regression on speed fixed, and AvroParquetSource struct bug fixed. I think this time should be faster than the previous best.
Marshalling to case classes will slow things down a lot though, expect throughput to halve at least, from the raw Seq[Any] case at least.

**Comment by sksamuel** [comment] 2017-01-13 09:04
See Type safe Frames #140

**Comment by sksamuel** [comment] 2017-01-13 09:11
Ok 1.1.1 has been released to central

**Comment by hannesmiller** [comment] 2017-01-13 09:29
Hi Sam,

Do the performances enhancements  on *AvroParquet* also apply to native *Parquet*?

I have some performance issues related with *JdbcSource -> HiveSink* with a Parquet dialect - I just want to establish this before embarking on the root cause of my import performance issues.

Cheers,
Hannes

**Comment by sksamuel** [comment] 2017-01-13 09:30
The hive sink uses native parquet but the regression and fix only apply to
reading parquet.

On 13 Jan 2017 09:29, "hannesmiller" <notifications@github.com> wrote:

Hi Sam,

Do the performances enhancements on *AvroParquet* also apply to native
*Parquet*?

I have some performance issues related with *JdbcSource -> HiveSink* with a
Parquet dialect - I just want to establish this before embarking on the
root cause of my import performance issues.

Cheers,
Hannes

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/sksamuel/eel-sdk/issues/180#issuecomment-272398771>,
or mute
the thread

**Comment by sksamuel** [comment] 2017-01-19 13:58
@tolomaus Did you manage to try 1.1.1 because that should be the fastest of them all.

**Comment by tolomaus** [comment] 2017-01-19 16:39
Ah great the conversion issue seems to be fixed!

I compared the performance of 1.1.1 with 1.0.1 but it's still a bit slower: 13s vs 11s (this is a different dataset so the results are not comparable to the previous figures)

**Comment by tolomaus** [comment] 2017-01-19 19:26
I had a closer look an it turns out that the conversion issue is still there, I didn't notice initially because I still had the ".tail" in my code which drops the badly converted head of the list.

After running it a couple of times, I can say that the performance is quite on par between both versions. At least the differences are too small to give a conclusive answer.

**Comment by sksamuel** [comment] 2017-01-27 04:00
I'll close this issue then if the performance is now back up. If you were able to open up a new ticket for the conversion error with a sample as I cannot seem to duplicate that would be good. If not I'll keep trying.

**Closed as completed by sksamuel** 2017-01-27 04:00 UTC
Labels: question

**Comment by tolomaus** [comment] 2017-01-27 08:12
Yes indeed, the performance is fine now. Ok I will see if I can reproduce the conversion error with a minimal scenario.
